server:
  port: 8088

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
        
  endpoint:
    health:
      show-details: always
      
spring:
  boot:
    admin:
      client:
        url: http://localhost:1111
        
# logging:
#   level:
#     de.codecentric.boot.admin.client: DEBUG

# internal:
#   service:
#     name: MS-AdminService
#     key: ${ADMIN_SERVICE_KEY}
internal:
  services:
    admin:
      name: MS-AdminService
      key: ${ADMIN_SERVICE_KEY}
